# Generated by Django 5.1.5 on 2025-01-24 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
